version: "3.9"
services:
  auth_service-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=auth_service
    ports:
      - "5432:5432"
    volumes:
      - auth_db:/var/lib/postgresql/data
  product-service-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=product_service
    ports:
      - "5433:5432"
    volumes:
      - product_db:/var/lib/postgresql/data

volumes:
  auth_db:
    driver: local
  product_db:
    driver: local
